### ISSUE TITLE
Is it possible to add a function to follow a creator?

### ISSUE THREAD

**Issue by anotherduckling** [jckli/picsiv#3]
The bot looks dope. Is it possible to add a function that will follow a creator? Maybe using rss feed.

**Comment by jckli** [comment]
Tbh, implementing this would be quite a lot of work. I don't think I'll be able to add this feature soon, but maybe in the future (no guarantees tho).

**Comment by anotherduckling** [comment]
i am not fully sure but this may help you https://docs.rsshub.app/en/social-media.html#pixiv .

**Comment by jckli** [comment]
Yeah, I know about it but the current api that I'm using, hibiscus, can already do it. It's not about whether it's possible, it's just quite a lot of work to implement. It would make the bot more resource intensive as well as it would need me to create a database.
